### ISSUE TITLE
hints for travisCI yml re difficulty installing 'units'

### ISSUE THREAD

**Issue by dankelley** [r-spatial/sf#1376]
(Prescript: I hope this question is not too open-ended.  If it is, I'd happily withdraw it.)

I am trying to figure out the proper `.travis.yml` to use, for an R package (https://github.com/dankelley/argoFloats/) that uses `sf` functions to determine whether some points are in a polygon.  (I am aware that I can do this with `sp` also, and I had done that until today, when I started trying to convert to `sf`.)

My `.travis.yml` is
```
language: r
warnings_are_errors: false
sudo: required
dist: trusty
after_success: travis_wait 30 Rscript -e 'library(covr); codecov(type="all")'

addons:
    apt:
        packages:
            - libnetcdf-dev
            - netcdf-bin

r_packages:
    - devtools
    - ncdf4
    - covr
    - sf

env:
    global:
        - _R_CHECK_FORCE_SUGGESTS_=False
        - _R_CHECK_CRAN_INCOMING=False
```
and, although my package builds, I get a warning re the `units` and `sf` packages (I do not use the former explicitly, but I guess it's requested for `sf`).

The details are at https://api.travis-ci.com/v3/job/320565060/log.txt in case anyone wants to look, and the main problem is as below.
```
Warning messages:
1: In install.packages(c("devtools", "ncdf4", "covr", "sf")) :
  installation of package â€˜unitsâ€™ had non-zero exit status
2: In install.packages(c("devtools", "ncdf4", "covr", "sf")) :
  installation of package â€˜sfâ€™ had non-zero exit status
```

I'd prefer not to turn off warnings, because I think warnings are helpful. I wonder if there's a special incantation I can put in my `.travis.yml` to make the above-stated warning go away?

My websearches did not turn up this problem, and I don't see it in searches within this issue forum, so I hope it's okay to ask.  But, again, I'd be happy if someone simply deleted it on the grounds of it being inappropriate.
