### ISSUE TITLE
Revisit CI workflows

### ISSUE THREAD

**Issue by kadyb** [r-spatial/sf#2129]
Maybe this is a good time to switch from `tic` to RStudio workflows if we only use GHA? It seems that everything works (Windows, MacOS, Ubuntu) and code is much less complicated.

rcmdcheck: https://github.com/kadyb/sf/actions/runs/4491306148
pkgdown: https://github.com/kadyb/sf/actions/runs/4491822298

<details>
<summary>rcmdcheck workflow</summary>

```
# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          rtools-version: '42'
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Install macOS system dependencies
        if: runner.os == 'macOS'
        run: brew install gdal proj

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
```
</details>
